### ISSUE TITLE
Weird visual bug

### ISSUE THREAD

**Issue by swz-git** [yare-io/bugs#1]
I'm using firefox 89.0.2 (64-bit)
![screenshot](https://swz.works/chest/bBAySD.gif)

**Comment by swz-git** [comment]
Another example when zooming
![screenshot](https://swz.works/chest/U_Jp2E.gif)

**Comment by L0laapk3** [comment]
Can reproduce on chrome 91.0.4472.124 on windows 20H2

**Comment by swz-git** [comment]
Fixed
